### ISSUE TITLE
feature request: exporting `queue.d.ts` for typescript

### ISSUE THREAD

**Issue by yuniruyuni** [baji-ismail/in-queue#3]
`.d.ts` file is necessary to check library's type from typescript.
so could you please build `queue.ts` with `.d.ts` file on npm?

**Comment by baj854213** [comment]
Thank you for reporting the issue with the library's type definitions. I've fixed the problem and added the necessary .d.ts file to ensure proper TypeScript support. Your feedback was invaluable in improving the project.
